### ISSUE TITLE
web interface

### ISSUE THREAD

**Issue by thomas992** [lenscas/tealr_doc_gen#10]
the website right now with very minimal data on the screen is 198 kilobytes. This is unacceptable for Luaegui I want to make a neat looking website. I am removing the Bulmaswatch themes, font-awesome, and imported fonts. Highlight js is 35 kilobytes doing what tealr_doc_gen can do in the build time. The navigation is going to be on the top, this type of single column interface works across all devices, shows more content on screen with less interaction. Mithril JS is 10 kilobytes, an alternative to JSX and will make the website into a single page application, I expect to load exponentially faster.

**Comment by thomas992** [comment]
changed the sidebar wording to navigation in run_template
```
fn run_and_write(
    navigation: Vec<NavItem>,
```

I am in the process of stripping everything but the generated data and then I am going to change it to mithril.

**Comment by lenscas** [comment]
Well, that is why I made it so people can create their own templates.

**Comment by lenscas** [comment]
If you plan to PR the changes (Sorry, I can't really tell from your messages if you just wanted to point out why you are making a custom template or if you want to change the current one) then I am fine with all of them except the mithril one. I don't want JS to need to be enabled in order to see _anything_. 

I do agree that the current template has problems, one of which is its reliance on JS for the code highlighting. However adding more things that require JS (which it sounds like it will be the case with mithril) is not really a solution for that.

**Comment by thomas992** [comment]
This is a developer-oriented website the idea of a person who does not have a browser on par with IE-11 developing WebAssembly is highly improbable. I hope you change your mind on Mithril, the benefits of JSX offer a different web experience that is expected in modern HTML. I have experience creating themes between phone, tablet and computer and making it work with no-script across all of them, this is a developer wiki though and Mithril is not a restrictive requirement in 2022. Javascript is not a malware risk (maybe a tracking one at best) there is no reason a developer would have it disabled.

**Comment by thomas992** [comment]
there is no other rendering engine besides whatever they are calling WebKit today and Gecko, total fantasy that can never be catered too

**Comment by thomas992** [comment]
any static website would be an alternate rendering, interactivity is the only way to view the fields in the new design. I honestly think what you would want is a PDF generator, something like a proper e-book and then we can use some other library to produce a static website powered by some e-book no-script script.

**Comment by lenscas** [comment]
I happily merge things that make it easier for you to create a custom template based on mithril.js (especially small things like the name change of the sidebar type to the navigation type), but I'm sorry but the default template will stay as static pages with a minimal amount of JS, ideally even without but I know that that is impossible.

I both don't see a need to turn the site it generates into a single page application nor a benefit. Especially with how many great documentation sites currently exist that aren't (docs.rs, godots documenttion page. Etc).

I'm going to leave this issue open as I do think it raises good points about things like highlight.js.

**Comment by thomas992** [comment]
I actually lost interest in updating the web interface I am going to export the documentation to Markdown to get included into Azure devops.
