### ISSUE TITLE
Compilation errors when running `cargo install tealr_doc_gen`

### ISSUE THREAD

**Issue by makspll** [lenscas/tealr_doc_gen#18]
Hi Lenscas!
I've noticed that running `cargo install tealr_doc_gen` uses the alpha-3 version of tealr causing some errors:
```rust
error[E0063]: missing field `type_doc` in initializer of `EnumGenerator`
  --> /home/makspll/.cargo/registry/src/github.com-1ecc6299db9ec823/tealr_doc_gen-0.2.0/src/run_template.rs:61:47
   |
61 |             type_members: TypeGenerator::Enum(EnumGenerator {
   |                                               ^^^^^^^^^^^^^ missing `type_doc`

error[E0283]: type annotations needed
   --> /home/makspll/.cargo/registry/src/github.com-1ecc6299db9ec823/tealr_doc_gen-0.2.0/src/run_template.rs:86:58
    |
86  |         instance_collector.add_instance("side_bar_types".into(), move |_| Ok(side_bar))?;
    |                            ------------                  ^^^^
    |                            |
    |                            required by a bound introduced by this call
    |
    = note: cannot satisfy `_: Into<Cow<'static, str>>`
```
It looks like running:
`cargo install tealr_doc_gen --git https://github.com/lenscas/tealr_doc_gen/`
works however.

Not sure if that is expected!

**Comment by lenscas** [comment]
that is... not expected. Thanks for the catch. Not sure what happened.

**Comment by makspll** [comment]
It seems so, now it's pulling the alpha 4 version, but I think it should be using the non-alpha tealr versions

**Comment by cery999** [comment]
it still occur

**Comment by lenscas** [comment]
the problem was that `cargo install` by default would install the latest non alpha version. Now that tealr_doc_gen v0.3.0 is released (no alpha!) this is fixed.
