### ISSUE TITLE
`page_root` is not respected in links 

### ISSUE THREAD

**Issue by makspll** [lenscas/tealr_doc_gen#20]
using page_root seems not to have an effect on links inside the documents. they all seem to point to `/<structure>`

**Comment by lenscas** [comment]
Is there a specific link that doesn't work? A lot of links are relative which means they don't need to know about `page_root`. For example the <a> over at https://github.com/lenscas/tealr_doc_gen/blob/91afd4a528e7f5b746ac3a6b299c422b42c05db6/base_template.etlua#L273

**Comment by makspll** [comment]
You can have a look at the site, as it's currently automatically built to this github page : https://github.com/makspll/bevy_mod_scripting_lua

I think the majority of links do not work. I built with the default config with only change being the name and page root settings (the work flows which built this are on the bevy_mod_scripting repo)

**Comment by makspll** [comment]
Actually never mind, page_root is correctly accounted for in the links, I just didn't realise documentation was being created nested under a folder and looked at the wrong output! Thanks!
